import { useState, useEffect, useRef } from 'react';
import PropTypes from 'prop-types';
import Link from 'next/link';
import cx from 'classnames';
import { getCartQuantity } from 'utils/checkout';
import { useCart } from 'hooks/store';

function useAnimation(predicate) {
  const [animate, setAnimate] = useState(false);
  const prevPredicate = useRef(null);

  useEffect(() => {
    if (prevPredicate.current !== null) setAnimate(true);
    prevPredicate.current = predicate;
  }, [predicate]);

  return [animate, setAnimate];
}

export default function Header({
  showMenu,
  showCart,
  reveal,
}) {
  const cart = useCart();
  const cartQuantity = getCartQuantity(cart);
  const [animate, setAnimate] = useAnimation(cartQuantity);

  return (
    <header>
      <button type="button" className="menu-button" onClick={showMenu}>
        <img className="hamburger-icon" src="/icons/menu.svg" alt="Menu" />
      </button>
      <Link href="/">
        <a className="brand">
          <img src="/brand.png" alt="Fustic brand" />
        </a>
      </Link>
      <button
        type="button"
        /**
         * Same key as animation predicate, so when animation is triggered,
         * the button is re-rendered
         */
        key={cartQuantity}
        className={cx('cart-button', { wobble: animate })}
        onAnimationEnd={() => setAnimate(false)}
        onClick={showCart}
      >
        Cart
        {!!cartQuantity && <span className="quantity">{cartQuantity}</span>}
      </button>
      <div className="items">
        <Link href="/">
          <a>Collections</a>
        </Link>
        <a className="wobble">About</a>
        <button
          type="button"
          /**
           * Same key as animation predicate, so when animation is triggered,
           * the button is re-rendered
           */
          key={cartQuantity}
          className={cx('cart-icon-button', { wobble: animate })}
          onAnimationEnd={() => setAnimate(false)}
          onClick={showCart}
        >
          <img src="/icons/cart.svg" alt="Cart" />
          {!!cartQuantity && <span className="quantity">{cartQuantity}</span>}
        </button>
      </div>

      <style jsx>
        {`
        /* ----------------------------------------------
        * Generated by Animista on 2020-8-25 21:30:15
        * Licensed under FreeBSD License.
        * See http://animista.net/license for more info.
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */

        /**
        * ----------------------------------------
        * animation wobble-hor-bottom
        * ----------------------------------------
        */
        @keyframes wobble {
          0%,
          100% {
            transform: translateX(0%);
            transform-origin: 50% 50%;
          }
          15% {
            transform: translateX(-1em) rotate(-6deg);
          }
          30% {
            transform: translateX(0.75em) rotate(6deg);
          }
          45% {
            transform: translateX(-0.75em) rotate(-3.6deg);
          }
          60% {
            transform: translateX(0.5em) rotate(2.4deg);
          }
          75% {
            transform: translateX(-0.25em) rotate(-1.2deg);
          }
        }

        header {
          position: fixed;
          top: 0;
          z-index: 1000;
          width: 100%;
          padding: var(--padding-header);

          display: grid;
          grid-template-columns: 1fr 1fr 1fr;
          grid-template-areas: "menu-button brand cart-button";
          align-items: center;

          .items {
            display: none;
          }

          .menu-button, .cart-button {
            background-color: transparent;
            border: none;
            padding: 0 7px;
          }

          .menu-button {
            grid-area: menu-button;
            justify-self: left;

            .hamburger-icon {
              width: 20px;
              height: 20px;
            }
          }

          .brand {
            grid-area: brand;
            justify-self: center;
            display: flex;
            align-items: center;

            img {
              height: var(--height-brand);
            }
          }

          .cart-button {
            grid-area: cart-button;
            justify-self: right;
            font-size: var(--fontsize-sm);
            text-transform: uppercase;
            opacity: ${reveal === 'cart' ? 0 : 1};

            .quantity {
              display: inline-block;
              background-color: #CC0000;
              border-radius: 999px;
              padding: 0.2em 0.4em;
              min-width: 1.5em;
              height: 1.5em;
              text-align: center;
              margin-left: 0.25em;
            }

            &.wobble {
              animation: wobble 0.8s both;
            }
          }

          @media screen and (min-width: 1200px) {
            grid-template-columns: 1fr 1fr;
            grid-template-areas: "brand items";

            .menu-button, .cart-button {
              display: none;
            }

            .brand {
              justify-self: left;
            }

            .items {
              grid-area: items;
              justify-self: right;

              display: grid;
              grid-template-columns: min-content min-content min-content;
              column-gap: 30px;

              text-transform: uppercase;

              > a {
                display: flex;
                align-items: center;
              }

              .cart-icon-button {
                width: max-content;

                img {
                  vertical-align: text-top;
                  width: calc(var(--fontsize-md) * 1.23);
                  height: calc(var(--fontsize-md) * 1.23);
                }

                .quantity {
                  display: inline-block;
                  background-color: #CC0000;
                  border-radius: 999px;
                  padding: 0.2em 0.4em;
                  min-width: 1.5em;
                  height: 1.5em;
                  text-align: center;
                  margin-left: 0.5em;
                }

                &.wobble {
                  animation: wobble 0.8s both;
                }
              }
            }
          }
        }
        `}
      </style>
    </header>
  );
}

Header.propTypes = {
  showMenu: PropTypes.func.isRequired,
  showCart: PropTypes.func.isRequired,
  reveal: PropTypes.string.isRequired,
};
